name: build-pytrends-json

on:
  schedule:
    - cron: '*/60 * * * *'    # каждые 60 минут
  workflow_dispatch:          # запуск «вручную» по кнопке

permissions:
  contents: write      # <-- эта строка новая

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install pytrends pandas lxml

      - run: python scripts/fetch.py

      - run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public || true
          git diff --cached --quiet && echo "No changes" || git commit -m "auto: update trends"
          # ↓ используем встроенный токен с правами write
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
