name: build-pytrends-json

on:
  schedule:
    - cron: '*/60 * * * *'    # каждые 60 минут
  workflow_dispatch:          # запуск «вручную» по кнопке

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install pytrends pandas lxml

      - run: python scripts/fetch.py

      - run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public
          git commit -m "auto: update trends" || echo "no changes"
          git push
